### ISSUE TITLE
Add sharing buttons

### ISSUE THREAD

**Issue by Airthee** [Airthee/how-long#20]
Allow user to share the website to social medias (only for mobile).

See https://sharingbuttons.io/

**Comment by ripoul** [comment]
https://sharingbuttons.io/ is not a good idee -> it's a dead project

**Comment by Airthee** [comment]
What do you suggest ?

**Comment by ripoul** [comment]
For the few code line to write I suggest you to do it your-self

**Comment by lgomesp** [comment]
@Airthee can I do this?

**Comment by Airthee** [comment]
Of course!
